### ISSUE TITLE
`pkgdown` no longer creates `tests_and_coverage` vignette

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#23] opened 2018-10-14 03:30 UTC
Since downloading the latest commits in `pkgdown` and `covrpage`, I can no longer get the `covrpage` vignette article to build.

This is the error- 
```
|- Building articles ------------------------------------------------------------
Reading 'vignettes/tests_and_coverage.Rmd'
simpleError in x[["class"]]: subscript out of bounds>
Error in x[["class"]] : subscript out of bounds
```

**Comment by IndrajeetPatil** [comment] 2018-10-14 13:41
``` r
library(covrpage)
library(pkgdown)

options(width = 200)
devtools::session_info()
#> - Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2018-10-14                  
#> 
#> - Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#>  package     * version     date       lib source                             
#>  assertthat    0.2.0       2017-04-11 [1] CRAN (R 3.5.0)                     
#>  backports     1.1.2       2017-12-13 [1] CRAN (R 3.5.0)                     
#>  base64enc     0.1-3       2015-07-28 [1] CRAN (R 3.5.0)                     
#>  callr         3.0.0       2018-08-24 [1] CRAN (R 3.5.1)                     
#>  cli           1.0.1       2018-09-25 [1] CRAN (R 3.5.1)                     
#>  commonmark    1.6         2018-09-30 [1] CRAN (R 3.5.1)                     
#>  covr          3.2.0.9000  2018-09-23 [1] Github (r-lib/covr@dc64171)        
#>  covrpage    * 0.0.60      2018-10-10 [1] Github (yonicd/covrpage@ac873f6)   
#>  crayon        1.3.4       2018-09-26 [1] Github (r-lib/crayon@3e751fb)      
#>  curl          3.2         2018-03-28 [1] CRAN (R 3.5.0)                     
#>  debugme       1.1.0       2017-10-22 [1] CRAN (R 3.5.0)                     
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 3.5.0)                     
#>  devtools      1.13.6.9000 2018-09-23 [1] Github (r-lib/devtools@74df201)    
#>  digest        0.6.18      2018-10-10 [1] CRAN (R 3.5.1)                     
#>  evaluate      0.12        2018-10-09 [1] CRAN (R 3.5.1)                     
#>  fs            1.2.6       2018-08-23 [1] CRAN (R 3.5.1)                     
#>  git2r         0.23.0      2018-07-17 [1] CRAN (R 3.5.1)                     
#>  glue          1.3.0       2018-09-17 [1] Github (tidyverse/glue@4e74901)    
#>  highr         0.7         2018-06-09 [1] CRAN (R 3.5.0)                     
#>  htmldeps      0.1.1       2018-09-17 [1] Github (rstudio/htmldeps@c1023e0)  
#>  htmltools     0.3.6       2017-04-28 [1] CRAN (R 3.5.0)                     
#>  knitr         1.20.19     2018-10-10 [1] Github (yihui/knitr@3abb642)       
#>  lazyeval      0.2.1       2017-10-29 [1] CRAN (R 3.5.0)                     
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 3.5.0)                     
#>  MASS          7.3-50      2018-04-30 [2] CRAN (R 3.5.1)                     
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 3.5.0)                     
#>  pkgbuild      1.0.1.9000  2018-10-01 [1] Github (r-lib/pkgbuild@446d70c)    
#>  pkgdown     * 1.1.0.9000  2018-10-12 [1] Github (r-lib/pkgdown@3b3188b)     
#>  pkgload       1.0.1       2018-10-11 [1] CRAN (R 3.5.1)                     
#>  prettyunits   1.0.2       2015-07-13 [1] CRAN (R 3.5.0)                     
#>  processx      3.2.0       2018-08-16 [1] CRAN (R 3.5.1)                     
#>  ps            1.1.0       2018-08-10 [1] CRAN (R 3.5.1)                     
#>  R6            2.3.0       2018-10-04 [1] CRAN (R 3.5.1)                     
#>  Rcpp          0.12.19     2018-10-01 [1] CRAN (R 3.5.1)                     
#>  remotes       2.0.0       2018-10-11 [1] CRAN (R 3.5.1)                     
#>  rex           1.1.2       2017-10-19 [1] CRAN (R 3.5.0)                     
#>  rlang         0.2.99.0000 2018-10-10 [1] Github (r-lib/rlang@fb09ff3)       
#>  rmarkdown     1.10.14     2018-10-10 [1] Github (rstudio/rmarkdown@dcc7d37) 
#>  roxygen2      6.1.0.9000  2018-09-13 [1] Github (klutometis/roxygen@cc34200)
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.5.0)                     
#>  sessioninfo   1.1.0       2018-09-25 [1] CRAN (R 3.5.1)                     
#>  stringi       1.2.4       2018-07-20 [1] CRAN (R 3.5.1)                     
#>  stringr       1.3.1       2018-05-10 [1] CRAN (R 3.5.0)                     
#>  testthat      2.0.1       2018-10-13 [1] CRAN (R 3.5.1)                     
#>  usethis       1.4.0.9000  2018-09-23 [1] Github (r-lib/usethis@1e3c6a6)     
#>  whisker       0.3-2       2013-04-28 [1] CRAN (R 3.5.0)                     
#>  withr         2.1.2       2018-03-15 [1] CRAN (R 3.5.0)                     
#>  xfun          0.3         2018-07-06 [1] CRAN (R 3.5.1)                     
#>  xml2          1.2.0       2018-01-24 [1] CRAN (R 3.5.0)                     
#>  yaml          2.2.0       2018-07-25 [1] CRAN (R 3.5.1)                     
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.1/library
```

<sup>Created on 2018-10-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by yonicd** [comment] 2018-10-14 14:40
i tried to run your main readme and can't get chunk `ggscatterstats2` to render.

`Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found`

**Comment by IndrajeetPatil** [comment] 2018-10-14 15:04
Strange. I don’t get any such error. This is an issue with Mac OS though:
https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon

What if you just build the vignette in question-
pkgdown::build_article(“tests_and_coverage”)

Does it work?

**Comment by yonicd** [comment] 2018-10-14 16:46
```r
> pkgdown::build_article('tests_and_coverage')
Reading 'vignettes/tests_and_coverage.Rmd'
Writing 'articles/tests_and_coverage.html'
```

**Comment by IndrajeetPatil** [comment] 2018-10-14 17:48
Hmm, I am guessing this issue affects only for the windows machines then.

**Comment by yonicd** [comment] 2018-10-14 18:13
I’m still surprised regular md can’t build in pkgdown. You can try to see if a similar file not created by covrpage has problems in pkgdown

**Comment by yonicd** [comment] 2018-10-14 19:04
you can also use [yonicd/rtravis](https://github.com/yonicd/rtravis) to test the new pkgdown master branch. it is the slimmed down version i made for r-lib to show them the old [warning](https://github.com/r-lib/pkgdown/issues/824) issue.

**Comment by yonicd** [comment] 2018-10-14 19:06
try updating your covrpage install. your hash seems outdated.

yours -> `#>  covrpage    * 0.0.60      2018-10-10 [1] Github (yonicd/covrpage@ac873f6)`
current master -> `58f193b `

**Comment by IndrajeetPatil** [comment] 2018-10-18 16:20
I can confirm that I am no longer getting this error once I downloaded the latest commit from `covrpage`. Thanks!

**Comment by yonicd** [comment] 2018-10-18 17:49
can you paste/attach the rmd file to an comment?

**Comment by IndrajeetPatil** [comment] 2018-10-18 17:52
Sure, here it is.

```
---
title: "Tests and Coverage"
date: "`r format(Sys.time(), '%d %B, %Y %H:%M:%S')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


This output is created by
[covrpage](https://github.com/yonicd/covrpage).

## Coverage

Coverage summary is created using the
[covr](https://github.com/r-lib/covr) package.

    ## - Tests Failed
    ##   Coverage statistics are approximations of the non-failing tests.
    ##   Use with caution
    ## 
    ##  For further investigation check in testthat summary tables.

| Object                                                                            | Coverage (%) |
| :-------------------------------------------------------------------------------- | :----------: |
| ggstatsplot                                                                       |    21.82     |
| [R/combine\_plots.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/combine_plots.R)                                        |     0.00     |
| [R/ggcoefstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/ggcoefstats.R)                                             |     0.00     |
| [R/ggcorrmat.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/ggcorrmat.R)                                                 |     0.00     |
| [R/gghistostats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/gghistostats.R)                                           |     0.00     |
| [R/ggpiestats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/ggpiestats.R)                                               |     0.00     |
| [R/grouped\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/grouped_ggbetweenstats.R)                      |     0.00     |
| [R/grouped\_ggcorrmat.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/grouped_ggcorrmat.R)                                |     0.00     |
| [R/grouped\_gghistostats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/grouped_gghistostats.R)                          |     0.00     |
| [R/grouped\_ggpiestats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/grouped_ggpiestats.R)                              |     0.00     |
| [R/helpers\_ggcoefstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggcoefstats.R)                            |     0.00     |
| [R/helpers\_ggcorrmat.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggcorrmat.R)                                |     0.00     |
| [R/helpers\_gghistostats\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_gghistostats_subtitles.R)     |     0.00     |
| [R/helpers\_ggpiestats\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggpiestats_subtitles.R)         |     0.00     |
| [R/helpers\_ggscatterstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggscatterstats.R)                      |     0.00     |
| [R/helpers\_messages.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_messages.R)                                  |     0.00     |
| [R/set\_cwd.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/set_cwd.R)                                                    |     0.00     |
| [R/helpers\_ggbetween\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggbetween_subtitles.R)           |    19.92     |
| [R/helpers\_ggscatterstats\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggscatterstats_subtitles.R) |    25.45     |
| [R/theme\_ggstatsplot.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/theme_ggstatsplot.R)                                |    29.27     |
| [R/grouped\_ggscatterstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/grouped_ggscatterstats.R)                      |    45.21     |
| [R/ggscatterstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/ggscatterstats.R)                                       |    51.42     |
| [R/switch\_functions.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/switch_functions.R)                                  |    59.09     |
| [R/helpers\_effsize\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_effsize_ci.R)                             |    64.58     |
| [R/helpers\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/helpers_ggbetweenstats.R)                      |    82.98     |
| [R/ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/R/ggbetweenstats.R)                                       |    86.48     |

<br>

## Unit Tests

Unit Test summary is created using the
[testthat](https://github.com/r-lib/testthat)
package.

| icon | file                                                                      |  n | time | error | failed | skipped | warning |
| :--- | :------------------------------------------------------------------------ | -: | ---: | ----: | -----: | ------: | ------: |
|      | [test\_anova\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_anova_subtitles.R)               |  4 | 1.06 |     0 |      0 |       0 |       0 |
|      | [test\_argument\_count.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_argument_count.R)                 |  1 | 0.03 |     0 |      0 |       0 |       0 |
|      | [test\_chisq\_v\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_chisq_v_ci.R)                        | 10 | 3.02 |     0 |      0 |       0 |       0 |
|      | [test\_cor\_test\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_cor_test_ci.R)                      | 12 | 0.51 |     0 |      0 |       0 |       0 |
| \+   | [test\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_ggbetweenstats.R)                  |  5 | 5.47 |     0 |      0 |       1 |       0 |
|      | [test\_grouped\_ggscatterstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_grouped_ggscatterstats.R) |  1 | 0.12 |     0 |      0 |       0 |       0 |
|      | [test\_lm\_effsize\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_lm_effsize_ci.R)                  |  9 | 3.33 |     0 |      0 |       0 |       0 |
|      | [test\_robcor\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_robcor_ci.R)                           |  8 | 0.18 |     0 |      0 |       0 |       0 |
|      | [test\_t\_test\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_t_test_subtitles.R)            |  1 | 0.42 |     0 |      0 |       0 |       0 |
|      | [test\_t1way\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_t1way_ci.R)                             |  5 | 4.00 |     0 |      0 |       0 |       0 |

<details open>

<summary> Show Detailed Test Results
</summary>

| icon | file                                                                             | context                 | test                                       | status  |  n | time |
| :--- | :------------------------------------------------------------------------------- | :---------------------- | :----------------------------------------- | :------ | -: | ---: |
|      | [test\_anova\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_anova_subtitles.R#L32_L35)              | anova\_subtitles        | anova subtitles work                       | PASS    |  4 | 1.06 |
|      | [test\_argument\_count.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_argument_count.R#L56_L59)                | argument\_count         | argument\_count is correct                 | PASS    |  1 | 0.03 |
|      | [test\_chisq\_v\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_chisq_v_ci.R#L45_L49)                       | chisq\_v\_ci            | chisq\_v\_ci works                         | PASS    | 10 | 3.02 |
|      | [test\_cor\_test\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_cor_test_ci.R#L45_L49)                     | cor\_test\_ci           | cor\_test\_ci works                        | PASS    | 12 | 0.51 |
|      | [test\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_ggbetweenstats.R#L9_L16)                  | ggbetweenstats          | error when x and outlier.label are same    | PASS    |  1 | 0.02 |
|      | [test\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_ggbetweenstats.R#L26_L36)                 | ggbetweenstats          | outlier.labeling works across vector types | PASS    |  3 | 3.33 |
| \+   | [test\_ggbetweenstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_ggbetweenstats.R#L89_L92)                 | ggbetweenstats          | ggbetweenstats works                       | SKIPPED |  1 | 2.12 |
|      | [test\_grouped\_ggscatterstats.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_grouped_ggscatterstats.R#L9_L17) | grouped\_ggscatterstats | grouped\_ggscatterstats works              | PASS    |  1 | 0.12 |
|      | [test\_lm\_effsize\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_lm_effsize_ci.R#L67_L71)                 | lm\_effsize\_ci         | lm\_effsize\_ci works                      | PASS    |  9 | 3.33 |
|      | [test\_robcor\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_robcor_ci.R#L39_L43)                          | robcor\_ci              | robcor\_ci works                           | PASS    |  8 | 0.18 |
|      | [test\_t\_test\_subtitles.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_t_test_subtitles.R#L43_L47)           | t\_test\_subtitles      | t-test subtitles work                      | PASS    |  1 | 0.42 |
|      | [test\_t1way\_ci.R](https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests/testthat/test_t1way_ci.R#L58)                                | t1way\_ci               | t1way\_ci works                            | PASS    |  5 | 4.00 |

</details>

<details>

<summary> Session Info </summary>

| Field    | Value                            |
| :------- | :------------------------------- |
| Version  | R version 3.5.1 (2018-07-02)     |
| Platform | x86\_64-w64-mingw32/x64 (64-bit) |
| Running  | Windows \>= 8 x64 (build 9200)   |
| Language | English\_United States           |
| Timezone | America/New\_York                |

| Package  | Version    |
| :------- | :--------- |
| testthat | 2.0.1      |
| covr     | 3.2.0.9000 |
| covrpage | 0.0.60     |

</details>



```

**Comment by yonicd** [comment] 2018-10-18 18:14
does that file render (`build_vignette()`)?

**Comment by yonicd** [comment] 2018-10-19 16:59
can you submit a reproducible in pkgdown (not covrpage md, but similar, ie simple md tables in a vignette)  that reproduces this error in windows?

**Comment by yonicd** [comment] 2018-10-19 17:21
i am not able to reproduce this problem on a windows machine

```r
> pkgdown::build_article('tests_and_coverage')
Reading 'vignettes/tests_and_coverage.Rmd'
Writing 'articles/tests_and_coverage.html'
> Sys.info()
             sysname              release              version             nodename              machine                login                 user       effective_user 
           "Windows" "Server >= 2012 x64"         "build 9200"        "IP-0A0A0A72"             "x86-64"      "jonathan.sidi"      "jonathan.sidi"      "jonathan.sidi" 
> system('git remote -v')
origin	https://github.com/yonicd/covrpage.git (fetch)
origin	https://github.com/yonicd/covrpage.git (push)
```

<details><summary>Session Info</summary>

```r
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       GMT0                        
 date     2018-10-19                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.2.0      2017-04-11 CRAN (R 3.3.3)                    
 backports    1.1.2      2017-12-13 CRAN (R 3.3.3)                    
 base       * 3.3.1      2016-06-21 local                             
 base64enc    0.1-3      2015-07-28 CRAN (R 3.3.1)                    
 callr        3.0.0      2018-08-24 CRAN (R 3.3.2)                    
 cli          1.0.1      2018-09-25 CRAN (R 3.3.2)                    
 commonmark   1.6        2018-09-30 CRAN (R 3.3.2)                    
 covr       * 3.2.1      2018-10-18 CRAN (R 3.3.2)                    
 covrpage   * 0.0.61     2018-10-19 local                             
 crayon       1.3.4      2017-09-16 CRAN (R 3.3.3)                    
 curl         3.2        2018-03-28 CRAN (R 3.3.3)                    
 datasets   * 3.3.1      2016-06-21 local                             
 desc         1.2.0      2018-05-01 CRAN (R 3.3.2)                    
 devtools     1.13.3     2017-08-02 CRAN (R 3.3.3)                    
 digest       0.6.18     2018-10-10 CRAN (R 3.3.2)                    
 evaluate     0.12       2018-10-09 CRAN (R 3.3.2)                    
 fs           1.2.6      2018-08-23 CRAN (R 3.3.2)                    
 git2r        0.23.0     2018-07-17 CRAN (R 3.3.2)                    
 graphics   * 3.3.1      2016-06-21 local                             
 grDevices  * 3.3.1      2016-06-21 local                             
 highr        0.7        2018-06-09 CRAN (R 3.3.2)                    
 htmldeps     0.1.1      2018-10-10 Github (rstudio/htmldeps@c1023e0) 
 htmltools    0.3.6      2017-04-28 CRAN (R 3.3.3)                    
 httr         1.3.1      2017-08-20 CRAN (R 3.3.3)                    
 knitr      * 1.20       2018-02-20 CRAN (R 3.3.3)                    
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.3.3)                    
 magrittr   * 1.5        2014-11-22 CRAN (R 3.3.1)                    
 MASS         7.3-45     2016-04-21 CRAN (R 3.3.1)                    
 memoise      1.1.0      2017-04-21 CRAN (R 3.3.3)                    
 methods    * 3.3.1      2016-06-21 local                             
 pillar       1.2.1      2018-02-27 CRAN (R 3.3.3)                    
 pkgdown      1.1.0.9000 2018-10-19 Github (r-lib/pkgdown@6e70f7b)    
 processx     3.2.0      2018-08-16 CRAN (R 3.3.2)                    
 ps           1.2.0      2018-10-16 CRAN (R 3.3.2)                    
 purrr        0.2.5      2018-05-29 CRAN (R 3.3.2)                    
 R6           2.3.0      2018-10-04 CRAN (R 3.3.2)                    
 Rcpp         0.12.19    2018-10-01 CRAN (R 3.3.2)                    
 rematch2     2.0.1      2017-06-20 CRAN (R 3.3.3)                    
 rex          1.1.2      2017-10-19 CRAN (R 3.3.3)                    
 rlang        0.2.2      2018-08-16 CRAN (R 3.3.2)                    
 rmarkdown    1.10.14    2018-10-10 Github (rstudio/rmarkdown@dcc7d37)
 roxygen2     6.0.1      2017-02-06 CRAN (R 3.3.3)                    
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.3.3)                    
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.1)                    
 stats      * 3.3.1      2016-06-21 local                             
 stringi      1.2.4      2018-07-20 CRAN (R 3.3.2)                    
 stringr      1.3.1      2018-05-10 CRAN (R 3.3.2)                    
 testthat   * 2.0.1      2018-10-13 CRAN (R 3.3.2)                    
 tibble       1.4.2      2018-01-22 CRAN (R 3.3.3)                    
 tools        3.3.1      2016-06-21 local                             
 utils      * 3.3.1      2016-06-21 local                             
 whisker      0.3-2      2013-04-28 CRAN (R 3.3.1)                    
 withr        2.1.2      2018-03-15 CRAN (R 3.3.3)                    
 xml2         1.2.0      2018-01-24 CRAN (R 3.3.3)                    
 yaml         2.2.0      2018-07-25 CRAN (R 3.3.2)
```
</details>

**Comment by yonicd** [comment] 2018-10-19 19:35
closing for now, until this can be replicated cleanly.

**Closed by yonicd** 2018-10-19 19:35 UTC

**Comment by yonicd** [comment] 2018-10-20 13:14
found the [bug](https://github.com/metrumresearchgroup/pkgdown/commit/3836984197179dd712138dbc2396527e4cb3131a), it was in `pkgdown:::prepend_class`. You can use our [fork](https://github.com/metrumresearchgroup/pkgdown) of pkgdown until r-lib fixes it.
